initial frontend commit
bxtsang/apphasia pull request #2
Opened 2020-12-17 18:18 UTC by arixpsy

resolve #1

2020-12-19 15:53 UTC, bxtsang requested changes

2020-12-19 15:53 UTC, bxtsang commented on frontend/cypress.json
> +}
newline character

2020-12-19 15:53 UTC, bxtsang commented on frontend/cypress/plugins/index.js
> +}
add newline char

2020-12-19 15:53 UTC, bxtsang commented on frontend/layouts/error.vue
> +    <h1 v-if="error.statusCode === 404">
just a qn, is error a global variable?

2020-12-19 15:53 UTC, bxtsang commented on frontend/nuxt.config.js
> +      }
should we take out themes and put it in a separate file?

2020-12-19 15:53 UTC, bxtsang commented on frontend/pages/inspire.vue
> +      </blockquote>
I am inspired

2020-12-20 06:14 UTC, arixpsy commented on frontend/layouts/error.vue
> +    <h1 v-if="error.statusCode === 404">
its a prop from the parent.
error.vue generated by nuxt.

2020-12-20 06:15 UTC, arixpsy commented on frontend/nuxt.config.js
> +      }
its generated by installing vuetify. This is already a config file so no point separating. overwrite of themes however will be done in a separate sass file.

2020-12-20 06:36 UTC, merged